name: asciicast2gif
description: asccicast2gif action

#asciicast2gif [-t theme] [-s speed] [-S scale] [-w cols] [-h rows] <input-json-path-or-url> <output-gif-path>


inputs:
  theme:
    description: "one of: asciinema, tango, solarized-dark, solarized-light, monokai (default: asciinema)"
    default: "asciinema"
    required: false
  speed:
    description: "animation speed (default: 1)"
    default: "1"
    required: false
  scale:
    description: "image scale / pixel density (default: 2)"
    default: "2"
    required: false
  columns:
    description: "clip terminal to specified number of columns (width)"
    default: "80"
    required: false
  rows:
    description: "clip terminal to specified number of rows (height)"
    default: "68"
    required: false
  file:
    description: "asccinema JSON file"
    required: true
  files:
    description: "glob pattern for multiple asccinema JSON files"
    required: false
  output:
    description: "gif output"
    default: "demo.gif"
    required: false

runs:
  using: docker
  image: ./Dockerfile
  env:
    ASCIINEMA_THEME: ${{ inputs.theme }}
    ASCIINEMA_SPEED: ${{ inputs.speed }}
    ASCIINEMA_SCALE: ${{ inputs.scale }}
    ASCIINEMA_COLUMNS: ${{ inputs.columns }}
    ASCIINEMA_ROWS: ${{ inputs.rows }}
    ASCIINEMA_JSON_FILE: ${{ inputs.file }}
    ASCIINEMA_GLOB_EXP: ${{ inputs.files }}
    ASCIINEMA_OUTPUT_FILE: ${{ inputs.output }}
