#!/usr/bin/env bash
echo "ASCCINEMA_JSON_FILE=${ASCCINEMA_JSON_FILE}"
cat $ASCCINEMA_JSON_FILE
NODE_TLS_REJECT_UNAUTHORIZED=0 /app/asciicast2gif -t ${ASCCINEMA_THEME} -s ${ASCCINEMA_SPEED} -S ${ASCCINEMA_SCALE} -w ${ASCCINEMA_COLUMNS} -h ${ASCCINEMA_ROWS} ${ASCCINEMA_JSON_FILE} ${ASCCINEMA_OUTPUT_FILE}
